### ISSUE TITLE
Unpublished plugins in plugin list

### ISSUE THREAD

**Issue by Gared** [ether/ether.github.com#15]
In the search results of tools/getPlugin.js you get a list of _all_ plugins beginning with "ep_".
Also those ones that are marked as deprecated or already unpublished. 
I haven't found any way to get these informations from npm. The only difference between published and unpublished plugins is the missing description.
Any ideas to fix this problem?

**Comment by JohnMcLear** [comment]
``(If module.description === "") return`` ?

**Comment by Gared** [comment]
This would be a workaround we could try if there is no better way for that...

**Comment by JohnMcLear** [comment]
npm shouldn't be showing unpublished modules in it's search results, I guess that's an upstream bug?

**Comment by JohnMcLear** [comment]
https://github.com/npm/npm/issues/4848

**Comment by JohnMcLear** [comment]
It's kinda funny, no one on the npm team actually seems to want to deal with the problems surrounding search, they really need to hire someone who can figure out a decent solution for them..  It's been "broken" for quite a few years now.

**Comment by Gared** [comment]
If npm don't want to change something we have to find a better way to handle our plugins...

**Comment by JohnMcLear** [comment]
Yea for now a ``if(description === "")`` will be fine..  All ep_ plugins are published w/ descriptions
