### ISSUE TITLE
Website is a blank screen when JS is disabled

### ISSUE THREAD

**Issue by TangentFoxy** [ether/ether.github.com#208]
I get that JS is useful for dynamic elements and such, but almost *nothing* on the homepage is dynamic. Why does the site fail to return anything without JS enabled?

**Comment by SamTV12345** [comment]
This website uses React. As such it requires JavaScript to initialize the components, do state changes etc.

**Comment by SamTV12345** [comment]
Can be closed. I switched the main page to NextJS. It is mostly static content and only serves JavaScript for the interactive parts :)

**Comment by TangentFoxy** [comment]
Thank you so much, I really appreciate making it more accessible.
