### ISSUE TITLE
Add release 1.6.4 to homepage

### ISSUE THREAD

**Issue by nashe** [ether/ether.github.com#23]
Everything is in the title :-) Actual version in the downloads section is still 1.6.3.

**Comment by muxator** [comment]
@nashe: I've seen it yesterday, thanks.

That's a really bug in the website's code and in  bin/createRelease.sh: it always links http://github.com/ether/etherpad-lite/zipball/master

**Comment by muxator** [comment]
Fixed with d0aa6c07706075d8f42c1c4bfee6f130622bfd56.
