### ISSUE TITLE
Publish an up-to-date torrent

### ISSUE THREAD

**Issue by nashe** [ether/ether.github.com#24]
The last version available through torrent download is 1.4.1. Being affected by various vulnerabilities (notably the ones fixed in 1.6.4), that would be nice to publish a torrent file for the last release.

I guess that the release procedures will need to be updated if they don't mention this point.

**Comment by muxator** [comment]
I was thinking of zapping the torrent download, I do not see many advantages in keeping it.
What about guaranteeing seeding?

Do we have any numbers about how many download via torrent we can estimate?

**Comment by muxator** [comment]
Torrents removed with change: 31b1a33d6749d96b89fda3d2d09a38c2bbfa912b.

The torrents were added with these changes in 2014 and never upgraded:
* 9c53dd9    (2014-09-07 00:23)
* c4a4907    (2014-05-26 19:54)
