### ISSUE TITLE
Serve etherpad.org with a valid TLS certificate

### ISSUE THREAD

**Issue by nashe** [ether/ether.github.com#25]
Etherpad's website is available over TLS, but with a certificate signed for _GitHub Pages_:
```
openssl s_client -connect etherpad.org:443
CONNECTED(00000006)
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHZTCCBk2gAwIBAgIQCZdSNOgyQkmb9dELcsqVHjANBgkqhkiG9w0BAQsFADBw
--- SNIP ---
02dtHR8UBT2Ei/dI0mKWK3m/Fkhrjw4f11CxGsbiwpSJ0S+yoeszuKx14LPJuCDA
eofxIM2iH/zoRLIkiPbKXzG2SHQG5H1f4w==
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=*.github.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
```

It seems that the Gist at https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b contains up-to-date steps to do serve it with a certificate of the foundation. It forces to use _Cloudflare_ but I'm not aware of any viable alternative as long etherpad.org is hosted on _GitHub Pages_.

**Comment by muxator** [comment]
Just a note: reading [this article](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors) I think that this could be solved via a DNS reconfiguration for the [apex domain](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) and for the [www subdomain](https://help.github.com/articles/setting-up-a-www-subdomain/).

The current configuration is different, indeed, but I have not yet looked closely enough:

```
$ dig www.etherpad.org +noall +answer
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> www.etherpad.org +noall +answer
;; global options: +cmd
www.etherpad.org.	293	IN	CNAME	etherpad.org.
etherpad.org.		293	IN	A	192.30.252.153
etherpad.org.		293	IN	A	192.30.252.154
```

**Comment by nashe** [comment]
Several statements of my initial messages are now invalid [since Let's Encrypt is now supported by GitHub Pages](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

**Comment by Gared** [comment]
HTTPS enforcement is now activated for etherpad.org
