### ISSUE TITLE
Reshape etherpad.org ?

### ISSUE THREAD

**Issue by seballot** [ether/ether.github.com#30]
Hi !
Just wondering, now colibris is the default skin, shall we change the etherpad screenshot on https://etherpad.org/ ?
Also, I could arrange quickly the https://etherpad.org/ design to be closer to colibris skin?
WDYT?

**Comment by muxator** [comment]
It would be great.

Improve as much as you feel necessary.
https://etherpad.org is a static site hosted on github pages. Its repo is https://github.com/ether/ether.github.com/.

Do not forget to include your credits. :)

**Comment by locness3** [comment]
I guess it should also be changed in ether/etherpad-lite?

**Comment by muxator** [comment]
> I guess it should also be changed in ether/etherpad-lite README ?

Right call, I have opened an issue in the Etherpad repo. @locness3, are you willing to help us working on https://github.com/ether/etherpad-lite/issues/3779?

**Comment by locness3** [comment]
I maybe can

**Comment by seballot** [comment]
Almost done, just need to fix responsiveness, will do tomorrow !

**Comment by seballot** [comment]
Hey, I'm adding some numbers on the website. Re instances and users, do you think they are correct?

![image](https://user-images.githubusercontent.com/17404254/80229808-3f423d00-8651-11ea-8749-76aecbcf251e.png)

Also, I'm wondering about the contact links : https://etherpad.org/#contact

is the IRC  really used?
Twitter: Last twit was 2017, should I remove the link?
The google mailing: not sure to understand its purpose, but seems to be still used correct?

**Comment by JohnMcLear** [comment]
Numbers are correct.
IRC is rarely used but it's useful to have.
Twitter updated
Google Mailing can prolly be dropped now, Google did a shit job maintaining it and it's mostly a burden.

**Comment by locness3** [comment]
@seballot Could you show us a screenshot of what you're doing?

**Comment by seballot** [comment]
ok thanks @JohnMcLear !

@locness3 yes here you are

![image](https://user-images.githubusercontent.com/17404254/80234464-8122b180-8658-11ea-80fd-4af43e67d45b.png)

**Comment by seballot** [comment]
Ok I just open the PR #31
